version: '3.2'
services:
  myproject-app:
    container_name: myproject
    restart: always
    build: .
    ports:
      - 4114:80
    depends_on:
      - mysql
    networks:
      - myproject-network
    volumes:
      - .:/var/www/html

  mysql:
    container_name: myproject-mysql
    image: mysql:5.7.23
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./__mysql-data:/var/lib/mysql
    networks:
      - myproject-network

  adminer:
    container_name: myproject-dbadmin
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 4224:8080
    networks:
      - myproject-network
networks:
  myproject-network:
